version: '3.4'

services:
  grpcservice:
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    container_name: grpcservice
    ports:
      -  80:80
      -  443:443
    env_file:
      - .env
  grpcclient:
    image: ${DOCKER_REGISTRY-}grpcclient
    build:
      context: .
      dockerfile: GrpcClient/Dockerfile
    container_name: grpcclient
    depends_on: 
      - grpcservice
    env_file:
      - .env